### ISSUE TITLE
Project Task List: launch phase

### ISSUE THREAD

**Issue by ebeshero** [DigitalMitford/DM_Journal_1819-1823#11]
- [x] Make a first-pass transcript of May 24 1823 to the next five entries @tec5271 
- [x] Second pass clean-up pass @tylerakam : Clean up mistakes: concentrating on the typescript only. Attempt adding
    *  `<persName>`
    * `<placeName>`
    * `<orgName>`
    *  `<bibl>` or `<title>` (these are used for referenced to published or written literary works)
    * All of these take `@ref` attributes that point into the site index (SI file)

- [x] Review the original handwritten MS photo-facsimile, and add XML comments if you notice anything missing. Use initials and the ISO date in your comments like this:
   * ALWAYS NOTE what page the entry is on in the handwriting PDF 
   * IF the typist marked something unclear, make a guess? (at least alert @ebeshero )
   * Look at the whole page and surroundings and notice if there's a big block of something that isn't represented in the typescript.
   * Add corrections as you can. Otherwise you'll do your work in XML comments.
  @jdh6067 

- [x] @SavannahRicks  Start attempting to add `@ref` or `@corresp` attributes with values pointing to the Digital Mitford Site Index (SI) file. OR noting if a name may not be mentioned there. Work with the current SI file at https://digitalmitford.org/si.xml
