### ISSUE TITLE
2023 Spring Digital Mitford Project Tasks 

### ISSUE THREAD

**Issue by ebeshero** [DigitalMitford/DM_Journal_1819-1823#16]
- [ ] Peer into Mitford's future when looking up unclear names. See https://github.com/DigitalMitford/DM_Journal_1819-1823/issues/1#issuecomment-1522469164 
- [x] @SavannahRicks will work on de-duping the back list entries in the Journal file. https://github.com/DigitalMitford/DM_Journal_1819-1823/issues/14 
     * Edit this issue and indicate how far you get.
     * For 2023-02-21, review against <https://digitalmitford.org/si.xml> (the published si file), and paste in any relevant entries you see, OR note if it's already covered there. 
     * Review all the listOrg entries. If already represented in either the si-local.xml OR the main si, or represented BETTER there, **please delete** the entries in the backlist.

- [x] @SavannahRicks will also review all the new entries (June 30 - July 31) and make polishing corrections 
- [x] When there is a discrepancy between the `@ref` attribute values in the Journal and the `si-local.xml` or `si.xml`, @SavannahRicks  will Find and Replace using the canonical identifier, being sure to begin these with a `#`. 

- [x] @SavannahRicks and @tylerakam will each check out new branches named thus:
     * srr-Review
     * tsa-Transcribe
 
- [x] @tylerakam will continue transcribing, following new protocols for date representation in Mitford's handwriting of 21 January 1820.
- [x] @tylerakam will go back to the Behrend-transcribed entries and make follow the new date protocols, just to represent the dates as Mitford wrote them, including the form work (with `<fw>`) when you see it. Don't worry about removing the `<add>` elements because we'll do that with XSLT. 
     * **Update** @tylerakam has removed the `<add>` elements back to early May 1820 b/c easy to do so while editing.
     * When form work appears inside an entry (in a page turn), let's put it at the end of the entry so it doesn't disrupt the reading flow, and add a `<note resp="your_id">....</note>` to explain that it appears in the middle of the previous entry. 
- [x] During Tuesday meetings we will first merge Tyler's branch into Savannah's, and the open a PR from Savannah's branch. 
- [ ] @ebeshero with help from @tylerakam and @SavannahRicks will write XSLT to update the date handling of the Journal per https://github.com/DigitalMitford/DM_Journal_1819-1823/issues/19

**Comment by tylerakam** [comment]
- [ ] On the changing of months, Mitford sometimes uses the full number, such as "first" or "second"
- [ ] At the end of March, going into April 1820, Mitford has an added phrase. I anticipated it to be along the lines of "& April 1820" but it looks like it says "God Bless Him." Further investigation needed.
- [ ] On Thursday 16th March, 1820, Mitford accidentally writes "at home" before she writes "Thursday 16th" I want to double check that I include this properly.
