### ISSUE TITLE
Milestone 5 Tasklist

### ISSUE THREAD

**Issue by ebeshero** [DigitalMitford/DM_Journal_1819-1823#7]
Some of these require persistent nagging of @ebeshero for help! :-)

- [ ] Pull in info from SI and backlist entries, and work on mouseover popups like on the Mitford letters only better.
- [x] @tec5271 continues modifying HTML output for nature entries. Do another output of just distinct values of all plant and animal references, and also see if we can output the SI + backlist info alongside them. 
- [x] @SavannahRicks pull in SI entries. Mess with the CSS. Consolidate the CSS from others so there's a single style unifying the site. 
- [x] @jdh6067 Read the outputs from the SI that the others are pulling, and look up and compile images that the team uses for guides to color and informative illustrations for the site.
     * Think of your project website as helping people to understand and "visit" Oxfordshire / Watlington / Reading (UK) / Berkshire
     * What can you find out about what the place was like in the 1820s or even just early 19th century? 
     * Keep track of image sources to credit 
     * Suggestion: Compile images in this issue. 
- [x]  @tylerakam Work on blocking / layout of reading views that don't take forever to load (chunking the portions of the journal)
- [ ] @ebeshero  bootstraps the JS + CSS to help with various things before presentation day
