### ISSUE TITLE
Milestone 4 Task List

### ISSUE THREAD

**Issue by ebeshero** [DigitalMitford/DM_Journal_1819-1823#8]
- [x] Look for pictures / color references / dye companies / pigments / plants / gardens in the **Berkshire county, England** : put together a pile of resources. You could open an issue and provide links for now.  @jdh6067 

- [x] XSLT Task 1: Push processing a reading view of the journal. Concentrate on the entries in the `//body` element first (you can ignore the `//front` for now. 
@tylerakam 
@jdh6067 

- [x] XSLT Task 2: Output all the journal entries that mention the Haywards in some way so we can find out more about inns in the area. 
@SavannahRicks 
- [x] XSLT Task 3: Output a list or table of all the distinct values of plants and animals mentioned in the journal. 
@ebeshero will augment this with a hook into the SI and back entries for the Journal so we can output information about each one. 
The goal: Output each plant / animal, with a list of journal entries that mention it, and some information from the SI about it. Possibly a picture of the plant/animal if we have it.
@tec5271 
- [x] HTML / CSS work playing with styling the outputs , colors, blocking etc
