### ISSUE TITLE
Milestone 3 Task List

### ISSUE THREAD

**Issue by ebeshero** [DigitalMitford/DM_Journal_1819-1823#9]
- [x] Make a first-pass transcript of May 24 1823 to the next seven entries @SavannahRicks 
- [x] Second pass clean-up pass  Clean up mistakes: concentrating on the typescript only. Attempt adding
    *  `<persName>`
    * `<placeName>`
    * `<orgName>`
    *  `<bibl>` or `<title>` (these are used for referenced to published or written literary works)
    * All of these take `@ref` attributes that point into the site index (SI file) @tec5271 

- [x] Review the original handwritten MS photo-facsimile, and add XML comments if you notice anything missing. Use initials and the ISO date in your comments like this:
   * ALWAYS NOTE what page the entry is on in the handwriting PDF 
   * IF the typist marked something unclear, make a guess? (at least alert @ebeshero )
   * Look at the whole page and surroundings and notice if there's a big block of something that isn't represented in the typescript.
   * Add corrections as you can. Otherwise you'll do your work in XML comments.
@tylerakam

- [x] @jdh6067  Start attempting to add `@ref` or `@corresp` attributes with values pointing to the Digital Mitford Site Index (SI) file. OR noting if a name may not be mentioned there. Work with the current SI file at https://digitalmitford.org/si.xml  
- [x] @jdh6067 with help from team: Raise questions on [this Issue](https://github.com/DigitalMitford/DM_Journal_1819-1823/issues/10) about any mystery names. 
* Do not point `@ref` attributes if you're not sure of an identification, but do record whatever you can find out. 
* If you can reasonably figure out a name (based on searching teh document or the Mitford Site Index, then use `@ref` attributes. All named entities take refs, *except* books: Mentions of a book get marked as `<bibl>`, and `<bibl>` takes a `@corresp` with same idea. 
* ANY xml:ids that you point to have to be preceded by a `#`. If Savannah is `@xml:id="srr"`, we point to her as `<persName ref="#srr>Savannah</persName>`.
